// AUTO-GENERATED by scripts/calendar/sync-dates.mts. Do not edit by hand.
// Source: deterministic calendar library, Gregorian year 2026.
// dateDisplay spans the event days; the eve (sundown before) is in eveDate.
// Regenerate: npm run dates:sync -- 2026   |   Verify: npm run dates:check
//
// (Shape reference for the pattern library: illustrative entries, regenerate
// from your own calendar authority.)

export interface CalendarDate {
  startDate: string;
  endDate: string;
  eveDate: string;
  dateDisplay: string;
  gregorianYear: number;
}

export const CALENDAR_DATES: Record<string, CalendarDate> = {
  "spring-festival": { startDate: "2026-04-02", endDate: "2026-04-09", eveDate: "2026-04-01", dateDisplay: "April 2-9, 2026", gregorianYear: 2026 },
  "early-summer-festival": { startDate: "2026-05-22", endDate: "2026-05-23", eveDate: "2026-05-21", dateDisplay: "May 22-23, 2026", gregorianYear: 2026 },
  "summer-fast": { startDate: "2026-07-02", endDate: "2026-07-02", eveDate: "2026-07-01", dateDisplay: "July 2, 2026", gregorianYear: 2026 },
  "quiet-season": { startDate: "2026-07-02", endDate: "2026-07-23", eveDate: "2026-07-01", dateDisplay: "July 2-23, 2026", gregorianYear: 2026 },
  "autumn-new-year": { startDate: "2026-09-12", endDate: "2026-09-13", eveDate: "2026-09-11", dateDisplay: "September 12-13, 2026", gregorianYear: 2026 },
  "day-of-atonement": { startDate: "2026-09-21", endDate: "2026-09-21", eveDate: "2026-09-20", dateDisplay: "September 21, 2026", gregorianYear: 2026 },
  "harvest-festival": { startDate: "2026-09-26", endDate: "2026-10-02", eveDate: "2026-09-25", dateDisplay: "September 26 - October 2, 2026", gregorianYear: 2026 },
  "winter-festival": { startDate: "2026-12-04", endDate: "2026-12-12", eveDate: "2026-12-03", dateDisplay: "December 4-12, 2026", gregorianYear: 2026 },
};
